[
uuid(c681d488-d850-11d0-8c52-00c04fd90f7e),
version(1.0),
]
interface DefaultIfName
{

    typedef struct Struct_68_t
    {
        char    StructMember0[6];
    }Struct_68_t;

    typedef struct Struct_100_t
    {
        char    StructMember0;
        char    StructMember1;
        struct Struct_68_t  StructMember2;
    [size_is(StructMember1)]/*[range(0,0)]*/ long StructMember3[];
        }Struct_100_t;

    typedef struct Struct_136_t
    {
        long    StructMember0;
        [unique][size_is(StructMember0)]/*[range(0,100)]*/ char *   StructMember1;
    }Struct_136_t;

    typedef struct Struct_152_t
    {
        long    StructMember0;
        [unique]struct Struct_100_t*    StructMember1;
        [unique]struct Struct_136_t*    StructMember2;
        [unique][string] wchar_t*   StructMember3;
    }Struct_152_t;

    typedef struct Struct_220_t
    {
        long    StructMember0;
        [unique] /* [DBG] FC_BOGUS_ARRAY */ [size_is(StructMember0)]/*[range(0,500)]*/  /*  */ struct Struct_152_t**    StructMember1;
    }Struct_220_t;

    typedef struct Struct_266_t
    {
        long    StructMember0;
        long    StructMember1;
        [unique][size_is(StructMember1)]/*[range(0,32768)]*/ char * StructMember2;
    }Struct_266_t;

    typedef struct Struct_282_t
    {
        long    StructMember0;
        [unique]struct Struct_100_t*    StructMember1;
        [unique]struct Struct_266_t*    StructMember2;
    }Struct_282_t;

    typedef struct Struct_346_t
    {
        long    StructMember0;
        [unique] /* [DBG] FC_BOGUS_ARRAY */ [size_is(StructMember0)]/*[range(0,500)]*/  /*  */ struct Struct_282_t**    StructMember1;
    }Struct_346_t;

    typedef struct Struct_392_t
    {
        long    StructMember0;
        [unique][size_is(StructMember0)]/*[range(0,266240)]*/ char *    StructMember1;
    }Struct_392_t;

    typedef struct Struct_462_t
    {
        [range(0,8)] long   StructMember0;
        [range(0,2048)] long    StructMember1;
        [unique][size_is(/* FC_EXPR */(StructMember1 + StructMember0))]/*[range(0,0)]*/ char *  StructMember2;
    }Struct_462_t;

    typedef struct Struct_492_t
    {
        long    StructMember0;
        [unique]struct Struct_220_t*    StructMember1;
        [unique]struct Struct_282_t*    StructMember2;
        [unique]struct Struct_392_t*    StructMember3;
    }Struct_492_t;

long Proc0_EfsRpcOpenFileRaw_Downlevel(
    [in] handle_t IDL_handle,
    [out][context_handle] void** arg_1, 
    [in][string] wchar_t* arg_2, 
    [in]long arg_3);

long Proc1_EfsRpcReadFileRaw_Downlevel(
    [in][context_handle] void* arg_0, 
    [out] char *arg_1);

long Proc2_EfsRpcWriteFileRaw_Downlevel(
    [in][context_handle] void* arg_0, 
    [in] char *arg_1);

void Proc3_EfsRpcCloseRaw_Downlevel(
    [in][out][context_handle] void** arg_0);

long Proc4_EfsRpcEncryptFileSrv_Downlevel(
    [in][string] wchar_t* arg_1);

long Proc5_EfsRpcDecryptFileSrv_Downlevel(
    [in][string] wchar_t* arg_1, 
    [in]long arg_2);

long Proc6_EfsRpcQueryUsersOnFile_Downlevel(
    [in][string] wchar_t* arg_1, 
    [out][ref]struct Struct_220_t** arg_2);

long Proc7_EfsRpcQueryRecoveryAgents_Downlevel(
    [in][string] wchar_t* arg_1, 
    [out][ref]struct Struct_220_t** arg_2);

long Proc8_EfsRpcRemoveUsersFromFile_Downlevel(
    [in][string] wchar_t* arg_1, 
    [in]struct Struct_220_t* arg_2);

long Proc9_EfsRpcAddUsersToFile_Downlevel(
    [in][string] wchar_t* arg_1, 
    [in]struct Struct_346_t* arg_2);

long Proc10_EfsRpcFileKeyInfoEx_Downlevel(
    [in][unique]struct Struct_282_t* arg_1, 
    [in]long arg_2, 
    [in]long arg_3);

long Proc11_EfsRpcFileKeyInfoEx_Downlevel(
    [in][string] wchar_t* arg_1, 
    [in][string] wchar_t* arg_2, 
    [in]long arg_3, 
    [in]long arg_4, 
    [in][unique]struct Struct_392_t* arg_5, 
    [in]long arg_6);

long Proc12_EfsRpcFileKeyInfo_Downlevel(
    [in][string] wchar_t* arg_1, 
    [in]long arg_2, 
    [out][ref]struct Struct_392_t** arg_3);

long Proc13_EfsRpcDuplicateEncryptionInfoFile_Downlevel(
    [in][string] wchar_t* arg_1, 
    [in][string] wchar_t* arg_2, 
    [in]long arg_3, 
    [in]long arg_4, 
    [in][unique]struct Struct_392_t* arg_5, 
    [in]long arg_6);

long Proc14_EfsRpcFileKeyInfoEx_Downlevel(
    [in]struct Struct_136_t* arg_1, 
    [in]struct Struct_462_t* arg_2);

long Proc15_EfsRpcAddUsersToFileEx_Downlevel(
    [in]long arg_1, 
    [in][unique]struct Struct_392_t* arg_2, 
    [in][string] wchar_t* arg_3, 
    [in]struct Struct_346_t* arg_4);

long Proc16_EfsRpcFileKeyInfoEx_Downlevel(
    [in]long arg_1, 
    [in][unique]struct Struct_392_t* arg_2, 
    [in][string] wchar_t* arg_3, 
    [in]long arg_4, 
    [out][ref]struct Struct_392_t** arg_5);

long Proc17_EfsRpcFileKeyInfoEx_Downlevel(
    [out][ref]struct Struct_392_t** arg_1);

long Proc18_EfsRpcFileKeyInfoEx_Downlevel(
    [in][string] wchar_t* arg_1, 
    [out][ref]struct Struct_392_t** arg_2);

long Proc19_EfsRpcFileKeyInfoEx_Downlevel(
    [in][string] wchar_t* arg_1, 
    [in][unique]struct Struct_392_t* arg_2, 
    [in]struct Struct_392_t* arg_3, 
    [in][unique]struct Struct_492_t* arg_4);

long Proc20_EfsRpcFlushEfsCache_Downlevel(
);
} 